[profile.release]
opt-level = 3
panic = "abort"

[workspace]
resolver = "2"
members = [
    "calendar_check",
    "llvm_buildbot_monitor",
]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
cast_possible_truncation = "warn"
manual_let_else = "warn"
must_use_candidate = "warn"
