[package]
name = "llvm_buildbot_monitor"
version = "0.1.0"
authors = ["George Burgess IV <george.burgess.iv@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 2
panic = "abort"

[dependencies]
reqwest = { version = "0.10.0-alpha.2", features = ["gzip", "json"] }
async-std = "1.0"
chrono = "0.4"
#clap = "2.33"
#libc = "0.2"
log = "0.4"
failure = "0.1"
#rand = "0.7"
#rmp-serde = "0.14"
#rust-crypto = "0.2.36"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple_logger = "1.3"
tokio = { version = "0.2.0-alpha.6", features = ["sync"] }
#twoway = "0.2"
serenity = "0.7"
