#!/bin/bash -eu
# Runs `cargo update`, runs local tests, pushes w/ automerge on success.

cd "$(dirname "$(readlink -m "$0")")/.."

if [[ -n "$(git status --porcelain)" ]]; then
  echo "There are uncommitted changes" >&2
  exit 1
fi

git fetch
branch_name=cargo-update

if [[ "$(git branch -r)" == *"github/${branch_name}"* ]]; then
  echo "Deleting remote branch..."
  git push github --delete "${branch_name}"
fi

if [[ "$(git branch --show-current 2>&1 || :)" != "main" ]]; then
  echo "Switching to main..."
  git switch main
  git pull
fi

cargo update
cargo test
git checkout -B "${branch_name}"
git commit -a -m 'Run cargo-update'
git push --set-upstream github HEAD:"${branch_name}"

pr_url=$(gh pr create \
  --title='Run cargo-update' \
  --body='Autogenerated by cargo-update-and-push.sh.')
echo "Posted update PR as ${pr_url}."

gh pr merge "${pr_url}" --auto --delete-branch --squash
echo "Set autosubmit."
